### ISSUE TITLE
这个项目感觉挺空的

### ISSUE THREAD

**Issue by slience-me** [liyupi/yuapi-backend-public#1]

**Comment by liyupi** [comment]
然而这个项目是帮助最多同学拿到 offer 的项目 😄 随便放几个截图
![image](https://github.com/liyupi/yuapi-backend-public/assets/26037703/5f57e04e-9b51-4082-a256-e5ecd4639ebf)
![image](https://github.com/liyupi/yuapi-backend-public/assets/26037703/54a8429c-0674-4f54-a9ba-e118d468dc13)
<img width="333" alt="image" src="https://github.com/liyupi/yuapi-backend-public/assets/26037703/436b6445-b245-4ff1-970e-3222fd18e8a0">
![image](https://github.com/liyupi/yuapi-backend-public/assets/26037703/8c7f1a0e-a335-4b6a-b4e8-739ed85e7a97)

**Comment by slience-me** [comment]
你真的非常厉害👍

**Comment by slience-me** [comment]
非常抱歉，我以为是开源的，我的理解错误
